### ISSUE TITLE
ValueError occurs when the local sun rises earlier than 12:00 UTC

### ISSUE THREAD

**Issue by Logthm** [mawinkler/uptonight#5]
## Description

If the local sun rises earlier than 12:00:00 UTC on this day, class ` SunMoon ` will set ` _sun_next_setting ` to 12:00:00 of the date. ( At line 226 in ` uptonight.py ` )

This will cause ` observing_start_time ` to have the wrong time format. ( At line 750 in ` uptonight.py ` )

And result in ` time_range ` not being obtained correctly. ( At line 785 in ` uptonight.py ` )

## Error message

```
uptonight  | Traceback (most recent call last):
uptonight  |   File "/root/.local/lib/python3.10/site-packages/astropy/time/core.py", line 597, in _get_time_fmt
uptonight  |     return cls(val, val2, scale, precision, in_subfmt, out_subfmt)
uptonight  |   File "/root/.local/lib/python3.10/site-packages/astropy/time/formats.py", line 159, in __init__
uptonight  |     val1, val2 = self._check_val_type(val1, val2)
uptonight  |   File "/root/.local/lib/python3.10/site-packages/astropy/time/formats.py", line 1055, in _check_val_type
uptonight  |     raise TypeError(
uptonight  | TypeError: Input values for datetime class must be datetime objects
uptonight  | 
uptonight  | The above exception was the direct cause of the following exception:
uptonight  | 
uptonight  | Traceback (most recent call last):
uptonight  |   File "/app/main.py", line 181, in <module>
uptonight  |     main()
uptonight  |   File "/app/main.py", line 167, in main
uptonight  |     calc(
uptonight  |   File "/app/uptonight/uptonight.py", line 785, in calc
uptonight  |     time_range = Time([observing_start_time, observing_end_time], scale="utc")
uptonight  |   File "/root/.local/lib/python3.10/site-packages/astropy/time/core.py", line 1866, in __init__
uptonight  |     self._init_from_vals(
uptonight  |   File "/root/.local/lib/python3.10/site-packages/astropy/time/core.py", line 535, in _init_from_vals
uptonight  |     self._time = self._get_time_fmt(
uptonight  |   File "/root/.local/lib/python3.10/site-packages/astropy/time/core.py", line 613, in _get_time_fmt
uptonight  |     raise ValueError(
uptonight  | ValueError: Input values did not match any of the formats where the format keyword is optional: {'datetime': TypeError('Input values for datetime class must be datetime objects'), 'ymdhms': ValueError('input must be dict or table-like'), 'iso': TypeError('Input values for iso class must be strings'), 'isot': TypeError('Input values for isot class must be strings'), 'yday': TypeError('Input values for yday class must be strings'), 'datetime64': TypeError('Input values for datetime64 class must be datetime64 objects'), 'fits': TypeError('Input values for fits class must be strings'), 'byear_str': TypeError('Input values for byear_str class must be strings'), 'jyear_str': TypeError('Input values for jyear_str class must be strings'), 'astropy_time': ValueError('cannot concatenate times unless all locations are set or no locations are set')}
uptonight exited with code 1

```

## Steps to Reproduce

1. Use ` config.yaml ` as followed:

```yaml
target_list: targets/GaryImm
output_dir: out
live_mode: false

location:
  longitude: 140d7m20s
  latitude: 29d21m14s
  elevation: 40
  timezone: Asia/Shanghai

environment:
  pressure: 1.013
  temperature: 20
  relative_humidity: 0.38
```

2. Run UpTonight

```
python3 main.py
```

## Additional Information

I changed line 226 in `upto,night.py` from `+ 12 * u.hour ` to `+ 10 * u.hour`, which made the program run correctly at my address.

**Comment by mawinkler** [comment]
It should be fixed now. Maybe you can give it a try?

**Comment by Logthm** [comment]
> It should be fixed now. Maybe you can give it a try?

Yes, now it work perfectly at my place!
