### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81

### ISSUE THREAD

**Issue by Jonny-T-cyber** [mawinkler/uptonight#9]
Hi,
I'm trying to run it on Windows 11.
After installing the requirements, launching main.py I get the following error:

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 12736: character maps to <undefined>`

Please, can you give me some suggestions?
Thanks

**This is the stack trace:**

2024-06-03 18:00:00 DEBUG (MainThread) [main] Location longitude: 45d28m00s
2024-06-03 18:00:00 DEBUG (MainThread) [main] Location latitude: 09d12m00s
2024-06-03 18:00:00 DEBUG (MainThread) [main] Location elevation: 0
2024-06-03 18:00:00 DEBUG (MainThread) [main] Location timezone: UTC
2024-06-03 18:00:00 DEBUG (MainThread) [main] Environment pressure: 0
2024-06-03 18:00:00 DEBUG (MainThread) [main] Environment temperature: 0
2024-06-03 18:00:00 DEBUG (MainThread) [main] Environment relative_humidity: 0
2024-06-03 18:00:00 DEBUG (MainThread) [main] Altitude constraint min: 30
2024-06-03 18:00:00 DEBUG (MainThread) [main] Altitude constraint max: 80
2024-06-03 18:00:00 DEBUG (MainThread) [main] Airmass constraint: 2
2024-06-03 18:00:00 DEBUG (MainThread) [main] Size constraint min: 10
2024-06-03 18:00:00 DEBUG (MainThread) [main] Size constraint max: 300
2024-06-03 18:00:00 DEBUG (MainThread) [main] Moon separation min: 45
2024-06-03 18:00:00 DEBUG (MainThread) [main] Moon separation use illumination: True
2024-06-03 18:00:00 DEBUG (MainThread) [main] Fraction of time observable threshold: 0.5
2024-06-03 18:00:00 DEBUG (MainThread) [main] Max number within threshold: 60
2024-06-03 18:00:00 DEBUG (MainThread) [main] North to East ccw: False
2024-06-03 18:00:00 DEBUG (MainThread) [main] Observation date: None
2024-06-03 18:00:01 DEBUG (MainThread) [main] Target list: targets/GaryImm
2024-06-03 18:00:01 DEBUG (MainThread) [main] Type filter:
2024-06-03 18:00:01 DEBUG (MainThread) [main] Output directory: out
2024-06-03 18:00:01 DEBUG (MainThread) [main] Mode: False
2024-06-03 18:00:01 INFO (MainThread) [main] UpTonight one-time calculation mode
2024-06-03 18:00:01 INFO (MainThread) [__init__] Calculating for: 06/03/2024 12:00:00
2024-06-03 18:00:01 INFO (MainThread) [__init__] UTC offset: 0.0
2024-06-03 18:00:11 INFO (MainThread) [__init__] Sun set astronomical: 06/03/2024 16:32:06
2024-06-03 18:00:11 INFO (MainThread) [__init__] Sun rise astronomical: 06/04/2024 01:20:43
2024-06-03 18:00:11 INFO (MainThread) [__init__] Moon illumination: 10%
2024-06-03 18:00:11 INFO (MainThread) [calc] Observing start time: 06/03/2024 16:32:06
2024-06-03 18:00:11 DEBUG (MainThread) [calc] Building targets lists
Traceback (most recent call last):
  File "D:\Desktop\UPTONIGHT\uptonight-main\main.py", line 186, in <module>
    main()
  File "D:\Desktop\UPTONIGHT\uptonight-main\main.py", line 171, in main
    calc(
  File "D:\Desktop\UPTONIGHT\uptonight-main\uptonight\uptonight.py", line 797, in calc
    targets = Targets(target_list)
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\UPTONIGHT\uptonight-main\uptonight\uptonight.py", line 59, in __init__
    self._input_targets, self._fixed_targets = self._create_target_list(target_list)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\UPTONIGHT\uptonight-main\uptonight\uptonight.py", line 98, in _create_target_list
    input_targets = Table.read(f"{target_list}.csv", format="ascii.csv")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Giovanni\AppData\Local\Programs\Python\Python312\Lib\site-packages\astropy\table\connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Giovanni\AppData\Local\Programs\Python\Python312\Lib\site-packages\astropy\io\registry\core.py", line 221, in read
    data = reader(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Giovanni\AppData\Local\Programs\Python\Python312\Lib\site-packages\astropy\io\ascii\connect.py", line 19, in io_read
    return read(filename, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Giovanni\AppData\Local\Programs\Python\Python312\Lib\site-packages\astropy\utils\decorators.py", line 604, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Giovanni\AppData\Local\Programs\Python\Python312\Lib\site-packages\astropy\utils\decorators.py", line 604, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Giovanni\AppData\Local\Programs\Python\Python312\Lib\site-packages\astropy\utils\decorators.py", line 604, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "C:\Users\Giovanni\AppData\Local\Programs\Python\Python312\Lib\site-packages\astropy\io\ascii\ui.py", line 387, in read
    table = fileobj.read()
            ^^^^^^^^^^^^^^
  File "C:\Users\Giovanni\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 12736: character maps to <undefined>

**Comment by mawinkler** [comment]
This look like a conversion error to me, but I never tested on Windows, to be honest. I will try to take a look as time permits.

**Comment by mawinkler** [comment]
If you set the environment variable

`PYTHONUTF8=1`

It should work with the current main.

On macOS and Linux, UTF-8 is the standard encoding already. But Windows still uses legacy encoding (e.g. cp1252, cp932, etc...) as system encoding.
When UTF-8 mode is enabled, Python uses UTF-8 as default encoding for text files instead of system encoding.
